DROP TABLE renters;
DROP TABLE cars;
DROP TABLE rent_contracts;
DROP TABLE permanent_renters_discounts;
DROP TABLE payments;

CREATE TABLE renters (
  RENTER_ID NUMBER PRIMARY KEY,
  SURNAME VARCHAR(200) NOT NULL,
  NAME VARCHAR(200) NOT NULL,
  PATRONYMIC VARCHAR(200),
  ADRESS VARCHAR(400) NOT NULL,
  PASSPORT_ID VARCHAR(20) NOT NULL UNIQUE,
  DRIVERS_LICENSE VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE cars (
  CAR_ID NUMBER PRIMARY KEY,
  MODEL VARCHAR(20) NOT NULL,
  ENGINE_VOLUME NUMBER(2, 1) NOT NULL,
  TYPE_OF_FUEL VARCHAR(20) NOT NULL,
  LICENSE_PLATE VARCHAR(20) NOT NULL UNIQUE,
  VEHICLE_NUMBER VARCHAR(200) NOT NULL UNIQUE,
  
  CONSTRAINT model_check CHECK (MODEL in ('fiesta', 'focus', 'mondeo', 'transit')),
  CONSTRAINT type_of_fuel_check CHECK (TYPE_OF_FUEL in ('benzine', 'diesel'))
);

CREATE TABLE rent_contracts (
  CONTRACT_ID NUMBER PRIMARY KEY,
  RENTER_ID NUMBER NOT NULL,
  CAR_ID NUMBER NOT NULL,
  RENT_STARTING_DATE DATE NOT NULL,
  RENT_ENDING_DATE DATE NOT NULL,
  SURNAME_OF_SECOND_DRIVER VARCHAR(200),
  NAME_OF_SECOND_DRIVER VARCHAR(200),
  PATRONYMIC_OF_SECOND_DRIVER VARCHAR(200),
  RENT_COST NUMBER(10, 2) NOT NULL,
  DISCOUNT NUMBER(2),
  FINAL_COST NUMBER(10, 2) NOT NULL,
  
  CONSTRAINT rent_contracts_fk_renter
        FOREIGN KEY (RENTER_ID)
        REFERENCES renters(RENTER_ID),
  CONSTRAINT rent_contracts_fk_car
        FOREIGN KEY (CAR_ID)
        REFERENCES cars(CAR_ID)
);

CREATE TABLE permanent_renters_discounts (
  RENTER_ID NUMBER NOT NULL,
  DISCOUNT_ASSIGN_DATE DATE NOT NULL,
  
  CONSTRAINT permanent_renters_discounts_fk_renter
        FOREIGN KEY (RENTER_ID)
        REFERENCES renters(RENTER_ID)
);

CREATE TABLE payments (
  PAYMENT_ID NUMBER PRIMARY KEY,
  RENTER_ID NUMBER NOT NULL,
  CONTRACT_ID NUMBER NOT NULL,
  DATE_OF_PAYMENT DATE NOT NULL,
  
  CONSTRAINT payments_fk_renter
        FOREIGN KEY (RENTER_ID)
        REFERENCES renters(RENTER_ID),
  CONSTRAINT payments_fk_contract
        FOREIGN KEY (CONTRACT_ID)
        REFERENCES rent_contracts(CONTRACT_ID)
);